enum TODO_STATUS {
  DONE = 'DONE',
  WIP = 'WIP',
  ARCHIVE = 'ARCHIVE',
  POOL = 'POOL'
}

enum TODO_FILTER {
  ALL = 'ALL',
  DONE = 'DONE',
  WIP = 'WIP',
  ARCHIVE = 'ARCHIVE',
  POOL = 'POOL'
}

type TODO_FILTERABLE = TODO_STATUS | TODO_FILTER

export { TODO_STATUS, TODO_FILTER, TODO_FILTERABLE }
